import Link from "next/link";

export const metadata = { title: "Privacy Policy — Artifacial" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-deep)] px-5 py-16 md:px-16">
      <div className="mx-auto max-w-3xl">
        {/* Back */}
        <Link href="/" className="mb-10 inline-flex items-center gap-1.5 text-sm text-[var(--text-muted)] transition-colors hover:text-[var(--text-secondary)]">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 18 9 12 15 6" /></svg>
          Back
        </Link>

        <h1 className="font-display text-4xl font-bold text-[var(--text-primary)]">Privacy Policy</h1>
        <div className="mt-2 text-sm text-[var(--text-muted)]">
          <span className="font-medium text-[var(--accent-amber)]">Artifacial.app</span>
          <span className="mx-2">·</span>
          Effective Date: March 28, 2026
          <span className="mx-2">·</span>
          Last Updated: March 28, 2026
        </div>

        <div className="mt-12 space-y-10">

          <Section id="1" title="1. Introduction">
            <p>This Privacy Policy describes how Artifacial.app ("we," "us," or "our") collects, uses, stores, and discloses information when you use our web-based AI content generation platform ("the Service"). By using the Service, you consent to the practices described in this policy.</p>
          </Section>

          <Section id="2" title="2. Information We Collect">
            <Subsection title="2.1 Account Information">
              <p>When you create an account through a third-party single sign-on (SSO) provider (such as Google), we receive basic profile information from that provider, which may include your name, email address, and profile picture. We do not receive or store your SSO password.</p>
            </Subsection>
            <Subsection title="2.2 Payment Information">
              <p>When you subscribe to a paid plan, payment is processed by Stripe, Inc. We do not directly collect, store, or have access to your full credit card number or banking details. Stripe may share with us limited transaction information such as the last four digits of your card, card brand, expiration date, billing address, and transaction history. For details on how Stripe handles your data, refer to <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[var(--accent-amber)] hover:underline">Stripe's Privacy Policy</a>.</p>
            </Subsection>
            <Subsection title="2.3 Usage Data">
              <p>We collect information about how you interact with the Service, including pages visited, features used, timestamps, device type, browser type, IP address, and referring URLs.</p>
            </Subsection>
            <Subsection title="2.4 Prompts and Generated Content">
              <p>We log the text prompts you submit and the content (images and videos) generated by the Service. This data is associated with your account. See Section 4 for how and why this data is retained.</p>
            </Subsection>
            <Subsection title="2.5 Age Confirmation">
              <p>We record your self-declared confirmation that you are at least 18 years of age.</p>
            </Subsection>
          </Section>

          <Section id="3" title="3. How We Use Your Information">
            <p>We use collected information for the following purposes:</p>
            <ul>
              <li><strong className="text-[var(--text-primary)]">Service delivery:</strong> To process your prompts, generate content, manage your account, and handle billing.</li>
              <li><strong className="text-[var(--text-primary)]">Safety and policy enforcement:</strong> To detect, prevent, and respond to violations of our Terms of Service and Acceptable Use Policy, including the creation of deepfake content, CSAM, and other prohibited material.</li>
              <li><strong className="text-[var(--text-primary)]">Legal compliance:</strong> To comply with applicable laws, regulations, and valid legal process, including cooperation with law enforcement.</li>
              <li><strong className="text-[var(--text-primary)]">Service improvement:</strong> To analyze usage patterns, diagnose technical issues, and improve the Service. Error and performance data is processed through Sentry for this purpose.</li>
              <li><strong className="text-[var(--text-primary)]">Communication:</strong> To send you transactional emails related to your account, subscription, or material changes to our policies.</li>
            </ul>
            <p>We do not use your data for targeted advertising. We do not sell your personal information.</p>
          </Section>

          <Section id="4" title="4. Data Retention">
            <Subsection title="4.1 Prompt and Generation Logs">
              <p>User prompts and generated content are retained for as long as necessary to fulfill the purposes described in this policy, including safety enforcement and legal compliance. Because the Service generates content that may be subject to legal scrutiny, prompt and generation logs may be retained for an extended period even after account deletion. We will retain this data for a minimum of twenty-four (24) months following the date of generation, or longer if required by law or ongoing legal proceedings.</p>
            </Subsection>
            <Subsection title="4.2 Account Information">
              <p>Account information is retained for as long as your account is active. If you delete your account, we will delete or anonymize your account information within 90 days, except to the extent that retention is required for legal compliance or as described in Section 4.1.</p>
            </Subsection>
            <Subsection title="4.3 Payment Records">
              <p>Transaction records are retained as required by applicable tax and financial regulations.</p>
            </Subsection>
          </Section>

          <Section id="5" title="5. How We Share Your Information">
            <p>We do not sell your personal information. We may share your information in the following circumstances:</p>
            <Subsection title="5.1 Service Providers">
              <p>We share data with third-party service providers that help us operate the Service, including:</p>
              <ul>
                <li><strong className="text-[var(--text-primary)]">Stripe, Inc.</strong> — payment processing</li>
                <li><strong className="text-[var(--text-primary)]">Sentry</strong> — error monitoring and performance tracking</li>
                <li><strong className="text-[var(--text-primary)]">AI model providers</strong> — to process your prompts and generate content (prompts are sent to these providers for processing)</li>
                <li><strong className="text-[var(--text-primary)]">Cloud hosting providers</strong> — to store and serve data</li>
                <li><strong className="text-[var(--text-primary)]">SSO/OAuth providers</strong> — to authenticate your identity</li>
              </ul>
              <p>These providers are contractually obligated to use your data only for the purposes of providing their services to us.</p>
            </Subsection>
            <Subsection title="5.2 Law Enforcement and Legal Obligations">
              <p>We will disclose your information, including prompts and generated content, to law enforcement or government agencies when required by valid legal process (subpoena, court order, or warrant), or when we have a good-faith belief that disclosure is necessary to prevent serious harm or illegal activity. We may also make voluntary reports to the National Center for Missing & Exploited Children (NCMEC) or other appropriate authorities.</p>
            </Subsection>
            <Subsection title="5.3 Business Transfers">
              <p>In the event of a merger, acquisition, or sale of assets, your information may be transferred to the acquiring entity. We will notify you of any such transfer and any changes to this Privacy Policy.</p>
            </Subsection>
          </Section>

          <Section id="6" title="6. Cookies and Tracking Technologies">
            <p>We use cookies and similar technologies to maintain session state, remember preferences, and collect usage analytics. You can manage cookie preferences through your browser settings. Disabling cookies may affect the functionality of the Service.</p>
            <p>We do not use third-party advertising cookies or trackers.</p>
          </Section>

          <Section id="7" title="7. Data Security">
            <p>We implement commercially reasonable technical and organizational measures to protect your data, including encryption in transit (TLS) and at rest, access controls, and regular security assessments. However, no system is completely secure, and we cannot guarantee absolute security.</p>
          </Section>

          <Section id="8" title="8. Your Rights">
            <p>Depending on your jurisdiction, you may have the following rights regarding your personal information:</p>
            <ul>
              <li><strong className="text-[var(--text-primary)]">Access:</strong> Request a copy of the personal information we hold about you.</li>
              <li><strong className="text-[var(--text-primary)]">Correction:</strong> Request correction of inaccurate information.</li>
              <li><strong className="text-[var(--text-primary)]">Deletion:</strong> Request deletion of your personal information, subject to our retention obligations described in Section 4.</li>
              <li><strong className="text-[var(--text-primary)]">Portability:</strong> Request your data in a portable format.</li>
              <li><strong className="text-[var(--text-primary)]">Objection:</strong> Object to certain processing of your data.</li>
            </ul>
            <p>To exercise any of these rights, contact us at <a href="mailto:tanner@claritydigital.dev" className="text-[var(--accent-amber)] hover:underline">tanner@claritydigital.dev</a>. We will respond within 30 days or as required by applicable law.</p>
            <p>Note that due to the nature of the Service and our legal obligations, we may not be able to delete prompt and generation logs even upon request. We will inform you if this applies.</p>
          </Section>

          <Section id="9" title="9. California Privacy Rights (CCPA)">
            <p>If you are a California resident, you have additional rights under the California Consumer Privacy Act:</p>
            <ul>
              <li>The right to know what personal information we collect and how it is used.</li>
              <li>The right to request deletion of personal information, subject to legal exceptions.</li>
              <li>The right to opt out of the sale of personal information. We do not sell personal information.</li>
              <li>The right to non-discrimination for exercising your privacy rights.</li>
            </ul>
          </Section>

          <Section id="10" title="10. Children's Privacy">
            <p>The Service is not intended for anyone under 18 years of age. We do not knowingly collect information from individuals under 18. If we become aware that we have collected data from a minor, we will take steps to delete that information and terminate the associated account.</p>
          </Section>

          <Section id="11" title="11. International Users">
            <p>The Service is operated from the United States. If you access the Service from outside the United States, your information will be transferred to, stored, and processed in the United States. By using the Service, you consent to this transfer. If you are located in the European Economic Area, the United Kingdom, or other regions with data transfer regulations, please be aware that U.S. data protection laws may differ from those in your jurisdiction.</p>
          </Section>

          <Section id="12" title="12. Changes to This Policy">
            <p>We may update this Privacy Policy from time to time. Material changes will be communicated via the email associated with your account or through a notice on the Service. Your continued use of the Service after such changes constitutes acceptance of the updated policy.</p>
          </Section>

          <Section id="13" title="13. Contact">
            <p>For questions or requests regarding this Privacy Policy, contact us at: <a href="mailto:tanner@claritydigital.dev" className="text-[var(--accent-amber)] hover:underline">tanner@claritydigital.dev</a></p>
          </Section>

        </div>

        {/* Footer nav */}
        <div className="mt-16 flex flex-wrap gap-4 border-t border-[var(--border-subtle)] pt-8 text-xs text-[var(--text-muted)]">
          <Link href="/terms" className="hover:text-[var(--text-secondary)]">Terms of Service</Link>
          <Link href="/acceptable-use" className="hover:text-[var(--text-secondary)]">Acceptable Use Policy</Link>
          <Link href="/" className="ml-auto hover:text-[var(--text-secondary)]">← Back to Artifacial</Link>
        </div>
      </div>
    </div>
  );
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={`section-${id}`} className="scroll-mt-8">
      <h2 className="mb-4 font-display text-xl font-bold text-[var(--text-primary)]">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-[var(--text-secondary)]">{children}</div>
    </section>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mt-5">
      <h3 className="mb-2 text-sm font-semibold text-[var(--text-primary)]">{title}</h3>
      <div className="space-y-2">{children}</div>
    </div>
  );
}
